"""Layout propagation in the throwaway graph, including real GPU reference images."""
from collections import Counter
import math

import numpy as np
import pytest
import meltygui_imgui as imgui

from conftest import _ensure_gl_context
from test_retained_gui_gpu import pixels
from meltygui.core.rendering.retained_gui_prototype import RetainedGui


@pytest.fixture
def graphics():
    _ensure_gl_context()


def scene(model, *, fixed_parent=False, horizontal=False):
    cache = RetainedGui()
    calls, ids = Counter(), {}

    def mark(name):
        calls[name] += 1
        ids[name] = cache.current

    @cache.gui(width=None, height=None)
    def leaf(input_value: object, draw_state=None, cache=None):
        mark('leaf')
        height = model['height']
        color = model.get('color', 0xFF0000FF)
        imgui.get_window_draw_list().add_rect_filled(0, 0, draw_state.width, height, color)
        imgui.dummy(draw_state.width, height)
        cache.region('leaf', (0, 0, draw_state.width, height))
        return False, input_value

    @cache.gui(width=20, height=13)
    def sibling(input_value: object, cache=None):
        mark('sibling')
        imgui.get_window_draw_list().add_rect_filled(0, 0, 20, 13, 0xFF00FF00)
        cache.region('sibling', (0, 0, 20, 13))
        return False, input_value

    @cache.gui(width=None, height=70 if fixed_parent else None)
    def owner(input_value: object):
        mark('owner')
        if model.get('show', True):
            leaf(None, width=35 if horizontal else None)
        if horizontal:
            imgui.same_line()
        sibling(None)
        return False, input_value

    @cache.gui(width=130, height=180)
    def root(input_value: object):
        mark('root')
        imgui.set_cursor_screen_pos((7, 9))
        owner(None)
        imgui.dummy(1, 3)
        # Deliberately generated by the ancestor: its location depends on height.
        x, y = imgui.get_cursor_screen_pos()
        imgui.get_window_draw_list().add_rect_filled(x, y, x + 100, y + 5, 0xFFFF0000)
        return False, input_value

    root(None)
    return cache, root, calls, ids


def raster(cache, node):
    _, _, w, h = cache.graph.info(node)['rect']
    return pixels(cache.gpu.texture(node), int(w), max(1, int(h)))


@pytest.mark.parametrize('fixed_parent', [False, True])
@pytest.mark.parametrize('horizontal', [False, True])
def test_grow_shrink_zero_and_fractional_match_full_render(graphics, fixed_parent, horizontal):
    model = {'height': 18.25}
    cache, root, calls, ids = scene(model, fixed_parent=fixed_parent, horizontal=horizontal)
    original_ids = ids.copy()
    texture = cache.gpu.texture(ids['leaf'])
    try:
        for height in [80.75, 2., 0., 0., 37.5, 9., 115., 4.]:
            before = calls.copy()
            old_owner_h = cache.graph.info(ids['owner'])['rect'][3]
            old_leaf_h = cache.graph.info(ids['leaf'])['rect'][3]
            model['height'] = height
            cache.invalidate_id(ids['leaf'])
            cache.flush()
            assert ids == original_ids
            assert cache.gpu.texture(ids['leaf']) == texture
            # ImGui snaps item extents to pixels; use its measured layout extent.
            assert cache.graph.info(ids['leaf'])['rect'][3] == math.floor(height)
            assert calls['leaf'] == before['leaf'] + 1
            assert calls['sibling'] == before['sibling']
            assert calls['owner'] == before['owner'] + int(old_leaf_h != math.floor(height))
            owner_h = cache.graph.info(ids['owner'])['rect'][3]
            assert calls['root'] == before['root'] + int(owner_h != old_owner_h)
            fresh, _, _, fresh_ids = scene(model, fixed_parent=fixed_parent, horizontal=horizontal)
            try:
                for name in ids:
                    assert cache.graph.info(ids[name])['rect'] == fresh.graph.info(fresh_ids[name])['rect']
                    np.testing.assert_array_equal(raster(cache, ids[name]), raster(fresh, fresh_ids[name]))
            finally:
                fresh.close()
            stats = cache.gpu.stats()
            settled = calls.copy()
            root(None)
            cache.flush()
            assert calls == settled and cache.gpu.stats() == stats
    finally:
        cache.close()


def test_pixel_only_change_does_not_execute_layout(graphics):
    model = {'height': 24.}
    cache, _, calls, ids = scene(model)
    try:
        before = calls.copy()
        model['color'] = 0xFFFFFF00
        cache.invalidate_id(ids['leaf'])
        cache.flush()
        assert calls == before + Counter(leaf=1)
        assert raster(cache, ids['root'])[150, 12, 1] > 250
    finally:
        cache.close()


def test_owner_removal_wins_over_queued_resize_and_frees_texture(graphics):
    model = {'height': 20.}
    cache, _, calls, ids = scene(model)
    try:
        leaf_id = ids['leaf']
        before = calls.copy()
        model.update(height=70., show=False)
        cache.invalidate_id(leaf_id)
        cache.invalidate_id(ids['owner'])
        cache.flush()
        assert calls['leaf'] == before['leaf']
        assert leaf_id not in cache.graph.nodes()
        assert leaf_id not in cache.contexts and leaf_id not in cache.records
        assert cache.gpu.texture(leaf_id) is None
        fresh, _, _, fresh_ids = scene(model)
        try:
            np.testing.assert_array_equal(raster(cache, ids['root']), raster(fresh, fresh_ids['root']))
        finally:
            fresh.close()
    finally:
        cache.close()


def test_width_change_rewraps_text_and_moves_cached_sibling(graphics):
    cache = RetainedGui()
    calls, ids = Counter(), {}

    @cache.gui(width=None, height=None)
    def paragraph(input_value: str, draw_state=None, cache=None):
        calls['paragraph'] += 1
        ids['paragraph'] = cache.current
        imgui.push_text_wrap_pos(draw_state.width)
        imgui.text_unformatted(input_value)
        imgui.pop_text_wrap_pos()
        return False, input_value

    @cache.gui(width=20, height=12)
    def tail(input_value: object, cache=None):
        calls['tail'] += 1
        ids['tail'] = cache.current
        return False, input_value

    @cache.gui(height=None)
    def root(input_value: str, cache=None):
        ids['root'] = cache.current
        paragraph(input_value)
        tail(None)
        return False, input_value

    value = 'Variable width text must wrap and move the next cached item without rerunning that item.'
    try:
        sizes = []
        for width in (300, 90, 300):
            root(value, width=width)
            cache.flush()
            sizes.append(cache.graph.info(ids['root'])['rect'][3])
            assert cache.graph.info(ids['paragraph'])['rect'][2] == width
            py = cache.graph.info(ids['paragraph'])['rect'][3]
            assert cache.graph.info(ids['tail'])['rect'][1] == py + 4
        assert sizes[1] > sizes[0] == sizes[2]
        assert calls == Counter(paragraph=3, tail=1)
    finally:
        cache.close()


def test_measured_portal_resize_does_not_reexecute_owner(graphics):
    cache = RetainedGui()
    height, calls, ids = [10.], Counter(), {}

    @cache.gui(width=50, height=None)
    def portal(input_value: object, cache=None):
        calls['portal'] += 1
        ids['portal'] = cache.current
        imgui.dummy(50, height[0])
        return False, input_value

    @cache.gui(width=60, height=None)
    def owner(input_value: object, cache=None):
        calls['owner'] += 1
        ids['owner'] = cache.current
        portal(None, melty_window=True, initial={'window_pos': (200, 100)})
        imgui.dummy(60, 12)
        return False, input_value

    try:
        owner(None)
        cache.graph.move_window(ids['portal'], 250, 130)
        height[0] = 45
        cache.invalidate_id(ids['portal'])
        cache.flush()
        assert calls == Counter(owner=1, portal=2)
        assert cache.graph.info(ids['portal'])['rect'] == (250., 130., 50., 45.)
        assert cache.graph.info(ids['owner'])['rect'][3] == 12
    finally:
        cache.close()


def test_failed_measurement_preserves_previous_geometry_and_retries(graphics):
    cache = RetainedGui()
    mode, ids = [10], {}

    @cache.gui(width=40, height=None)
    def view(input_value: object, cache=None):
        ids['view'] = cache.current
        imgui.dummy(40, abs(mode[0]))
        if mode[0] < 0:
            raise ValueError('body failed')
        return False, input_value

    try:
        view(None)
        texture = cache.gpu.texture(ids['view'])
        old = raster(cache, ids['view'])
        mode[0] = -60
        cache.invalidate_id(ids['view'])
        with pytest.raises(ValueError, match='body failed'):
            cache.flush()
        assert cache.graph.info(ids['view'])['rect'][3] == 10
        np.testing.assert_array_equal(raster(cache, ids['view']), old)
        mode[0] = 60
        cache.flush()
        assert cache.graph.info(ids['view'])['rect'][3] == 60
        assert cache.gpu.texture(ids['view']) == texture
    finally:
        cache.close()


def test_result_replay_and_resize_settle_together_once(graphics):
    cache = RetainedGui()
    model, ids, edits, calls = {'value': 1}, {}, [], Counter()

    @cache.gui(width=40, height=None)
    def number(input_value: int, cache=None, view_events=None):
        calls['number'] += 1
        ids['number'] = cache.current
        value = input_value + int(view_events.get('increment', False))
        imgui.dummy(40, value * 15)
        return value != input_value, value

    @cache.gui(width=60, height=None)
    def owner(input_value: dict, cache=None):
        ids['owner'] = cache.current
        changed, value = number(input_value['value'])
        if changed:
            edits.append(value)
        input_value['value'] = value
        return changed, input_value

    try:
        owner(model)
        cache.send(ids['number'], 'increment')
        cache.flush()
        assert model['value'] == 2 and edits == [2]
        assert cache.graph.info(ids['owner'])['rect'][3] == 30
        assert calls['number'] == 2
        assert owner(model)[0] is True
        assert owner(model)[0] is False
        assert edits == [2] and calls['number'] == 2
    finally:
        cache.close()


def test_keyed_reorder_insert_remove_and_shared_aliases(graphics):
    cache = RetainedGui()
    order, model, ids, calls = ['a', 'b', 'c'], {'height': 12}, {}, Counter()

    @cache.gui(width=40, height=None)
    def item(input_value: dict, name='', cache=None):
        ids[name] = cache.current
        calls[name] += 1
        imgui.get_window_draw_list().add_rect_filled(0, 0, 40, input_value['height'],
                                                   {'a': 0xFF0000FF, 'b': 0xFF00FF00,
                                                    'c': 0xFFFF0000, 'd': 0xFFFFFFFF}[name])
        imgui.dummy(40, input_value['height'])
        return False, input_value

    @cache.gui(width=50, height=None)
    def root(input_value: object, cache=None):
        ids['root'] = cache.current
        for name in order:
            item(model, key=name, name=name)
        return False, input_value

    try:
        root(None)
        original = ids.copy()
        order[:] = ['c', 'a', 'd']
        cache.invalidate_id(ids['root'])
        cache.flush()
        assert ids['a'] == original['a'] and ids['c'] == original['c']
        assert original['b'] not in cache.graph.nodes()
        assert calls == Counter(a=1, b=1, c=1, d=1)
        assert [cache.graph.info(ids[k])['rect'][1] for k in order] == [0, 16, 32]
        model['height'] = 25
        assert cache.invalidate(model) == 3
        cache.flush()
        assert calls == Counter(a=2, b=1, c=2, d=2)
        assert [cache.graph.info(ids[k])['rect'][1] for k in order] == [0, 29, 58]
        assert cache.graph.info(ids['root'])['rect'][3] == 83
        result = raster(cache, ids['root'])
        assert tuple(result[-8, 8]) == (0, 0, 255, 255)
        assert tuple(result[-37, 8]) == (255, 0, 0, 255)
        assert tuple(result[-66, 8]) == (255, 255, 255, 255)
    finally:
        cache.close()


def test_hit_regions_follow_reflow_and_obey_fixed_parent_clip(graphics):
    model = {'height': 12.}
    cache, _, _, ids = scene(model, fixed_parent=True)
    try:
        sibling = ids['sibling']
        cache.pointer((12, 9 + 16 + 5))
        assert cache.hover == (sibling, 'sibling')
        model['height'] = 35
        cache.invalidate_id(ids['leaf'])
        cache.flush()
        # Same pointer sample must be retested after layout moves its target.
        cache.pointer((12, 9 + 16 + 5))
        assert cache.hover == (ids['leaf'], 'leaf')
        cache.pointer((12, 9 + 39 + 5))
        assert cache.hover == (sibling, 'sibling')
        model['height'] = 90
        cache.invalidate_id(ids['leaf'])
        cache.flush()
        cache.pointer((12, 9 + 94 + 5))
        assert cache.hover is None
    finally:
        cache.close()


def test_multiple_root_layout_is_settled_before_next_host_item(graphics):
    from conftest import begin_frame, end_frame
    model = {'height': 16.}
    cache, root, _, ids = scene(model)
    cache.auto_layout = True
    try:
        begin_frame()
        imgui.set_next_window_size(500, 400)
        imgui.begin('immediate host')
        imgui.set_cursor_screen_pos((0, 0))
        with cache.frame():
            root(None, height=None)
            initial_h = cache.graph.info(ids['root'])['rect'][3]
        imgui.end()
        end_frame()
        model['height'] = 70
        cache.invalidate_id(ids['leaf'])
        begin_frame()
        imgui.begin('immediate host')
        imgui.set_cursor_screen_pos((0, 0))
        with cache.frame():
            root(None, height=None)
            extent = cache.graph.info(ids['root'])['rect'][3]
            assert extent > initial_h
            assert imgui.get_cursor_screen_pos()[1] == extent + 4
        imgui.end()
        end_frame()
    finally:
        cache.close()


@pytest.mark.parametrize('bad', [-1, float('nan'), float('inf')])
def test_invalid_constraints_fail_without_declaring_nodes(bad):
    cache = RetainedGui(graphics=False)

    @cache.gui
    def view(input_value: object):
        return False, input_value

    try:
        with pytest.raises(ValueError):
            view(None, height=bad)
        assert cache.graph.nodes() == []
    finally:
        cache.close()


def test_min_max_height_stop_propagation_until_extent_changes(graphics):
    cache = RetainedGui()
    height, calls, ids = [5], Counter(), {}

    @cache.gui(width=40, height=None, min_height=20, max_height=60)
    def child(input_value: object, cache=None):
        calls['child'] += 1
        ids['child'] = cache.current
        imgui.dummy(40, height[0])
        return False, input_value

    @cache.gui(width=50, height=None)
    def owner(input_value: object, cache=None):
        calls['owner'] += 1
        ids['owner'] = cache.current
        child(None)
        return False, input_value

    try:
        owner(None)
        for extent, expected, owner_calls in [(10, 20, 1), (45, 45, 2), (80, 60, 3),
                                               (95, 60, 3), (30, 30, 4)]:
            height[0] = extent
            cache.invalidate_id(ids['child'])
            cache.flush()
            assert cache.graph.info(ids['owner'])['rect'][3] == expected
            assert calls['owner'] == owner_calls
            assert cache.states[ids['child']].content_height == extent
            assert cache.states[ids['child']].height == expected
    finally:
        cache.close()


def test_deep_layout_chain_is_not_mistaken_for_feedback_cycle():
    cache = RetainedGui(graphics=False)
    extent, calls, ids = [10], Counter(), {}

    def make(level, child):
        @cache.gui(width=40, height=None)
        def view(input_value: object, draw_state=None, cache=None):
            ids[level] = cache.current
            calls[level] += 1
            draw_state.height = child(None, return_extras=True)[2].height + 1 if child else extent[0]
            return False, input_value
        return view

    root = None
    for level in range(80):
        root = make(level, root)
    try:
        root(None)
        extent[0] = 25
        cache.invalidate_id(ids[0])
        cache.flush()
        assert cache.graph.info(ids[79])['rect'][3] == 104
        assert set(calls.values()) == {2}
    finally:
        cache.close()


def test_feedback_cycle_fails_with_identifiable_diagnostics():
    cache = RetainedGui(graphics=False)
    cycle, ids = [False], []

    @cache.gui(height=None)
    def unstable(input_value: object, draw_state=None, cache=None):
        ids[:] = [cache.current]
        draw_state.height = 20
        if cycle[0]:
            cache.invalidate_id(cache.current)
        return False, input_value

    try:
        unstable(None)
        cycle[0] = True
        cache.invalidate_id(ids[0])
        with pytest.raises(RuntimeError, match='did not converge.*unstable'):
            cache.flush()
    finally:
        cache.close()


def test_new_width_does_not_get_lost_while_returned_edit_is_pending():
    cache = RetainedGui(graphics=False)
    ids, widths = [], []

    @cache.gui(height=None)
    def view(input_value: int, draw_state=None, cache=None, view_events=None):
        ids[:] = [cache.current]
        widths.append(draw_state.width)
        value = input_value + int(view_events.get('increment', False))
        draw_state.height = value * 10
        return value != input_value, value

    try:
        view(1, width=300)
        cache.send(ids[0], 'increment')
        cache.flush()
        # The caller still echoes the old scalar while also changing constraints.
        assert view(1, width=90) == (True, 2)
        assert widths == [300, 300, 90]
        assert cache.graph.info(ids[0])['rect'][2:] == (90, 20)
        assert view(2, width=90) == (False, 2)
        assert widths == [300, 300, 90]
    finally:
        cache.close()


def test_measured_background_fills_new_bounds_with_correct_nested_alpha(graphics):
    cache = RetainedGui()
    extent, calls, ids = [8], Counter(), {}

    @cache.gui(width=30, height=None, tint=(1., 0., 0., .5))
    def child(input_value: object, cache=None):
        calls['child'] += 1
        ids['child'] = cache.current
        imgui.dummy(30, extent[0])
        return False, input_value

    @cache.gui(width=40, height=None, tint=(0., 0., 1., 1.))
    def parent(input_value: object, cache=None):
        calls['parent'] += 1
        ids['parent'] = cache.current
        child(None)
        return False, input_value

    try:
        parent(None)
        for height in (75, 3, 44):
            extent[0] = height
            before = calls.copy()
            cache.invalidate_id(ids['child'])
            cache.flush()
            assert calls == before + Counter(child=1, parent=1)
            # The bottom row is newly measured, not the old draw_state.height.
            np.testing.assert_allclose(raster(cache, ids['child'])[0, 5], [255, 0, 0, 128], atol=1)
            np.testing.assert_allclose(raster(cache, ids['parent'])[0, 5], [128, 0, 127, 255], atol=1)
            assert tuple(raster(cache, ids['parent'])[0, 35]) == (0, 0, 255, 255)
    finally:
        cache.close()


def test_seeded_layout_transitions_match_fresh_render_and_retire_resources(graphics):
    import random
    rng = random.Random(42)
    model = {'height': 12., 'show': True}
    cache, root, _, ids = scene(model)
    try:
        for step in range(80):
            previous_show = model['show']
            model.update(height=float(rng.randrange(0, 130)), show=rng.random() > .2,
                         color=rng.choice([0xFF0000FF, 0xFF00FF00, 0xFFFFFF00]))
            if previous_show != model['show']:
                cache.invalidate_id(ids['owner'])
            if ids.get('leaf') in cache.records:
                cache.invalidate_id(ids['leaf'])
            cache.flush()
            fresh, _, _, fresh_ids = scene(model)
            try:
                np.testing.assert_array_equal(raster(cache, ids['root']), raster(fresh, fresh_ids['root']),
                                              err_msg=f'transition {step}: {model}')
                assert len(cache.records) == len(fresh.records)
                assert set(cache.contexts) == set(cache.records) == set(cache.graph.nodes())
            finally:
                fresh.close()
            calls = {node: cache.graph.info(node)['executions'] for node in cache.graph.nodes()}
            stats = cache.gpu.stats()
            root(None)
            cache.flush()
            assert {node: cache.graph.info(node)['executions'] for node in cache.graph.nodes()} == calls
            assert cache.gpu.stats() == stats
    finally:
        cache.close()
