"""Symbol access to @render_func renderers without importing their module.

`RenderFuncs.draw_type` returns a lazy handle that resolves at call time from
Melty.render_funcs_by_name (auto-populated by the @render_func decorator). This
sidesteps import cycles: referencing a render func here never triggers an import
of whatever heavy module defines it.

CodeGenerator regenerates the _RenderFuncs class in THIS file so every registered
render func shows up as a real, IDE-visible member — kept in its own file so the
generator only ever rewrites this small module, never melty.py.
"""

from src.lsd.gl_gui.melty import Melty


class _LazyRenderFunc:
    """A by-name handle to a @render_func, resolved on first use.

    Behaves like the render func itself: callable with the same signature and
    carrying the right __name__ (the view system reads that). Resolution is
    deferred to call time, by which point every module has imported and
    self-registered into Melty.render_funcs_by_name — so referencing one of
    these never triggers an import and never participates in an import cycle.
    """

    __slots__ = ("__name__", "_fn")

    def __init__(self, name):
        self.__name__ = name
        self._fn = None

    def _resolve(self):
        if self._fn is None:
            fn = Melty.render_funcs_by_name.get(self.__name__)
            if fn is None:
                raise AttributeError(
                    f"No @render_func named {self.__name__!r} is registered")
            self._fn = fn
        return self._fn

    def __call__(self, *args, **kwargs):
        return self._resolve()(*args, **kwargs)

    def __getattr__(self, item):
        # Forward real attributes (e.g. _load_data/_save_data) to the resolved
        # func, but never dunders; copy/pickle probes (__deepcopy__, etc.) must
        # fall through to default handling rather than force early resolution.
        if item.startswith("__") and item.endswith("__"):
            raise AttributeError(item)
        return getattr(self._resolve(), item)


class _RenderFuncs:
    """`RenderFuncs.draw_type` -> a _LazyRenderFunc handle, no import required.

    The annotated members below are generated by CodeGenerator (one per
    registered @render_func) so IDEs autocomplete RenderFuncs.<name>. They are
    string annotations — never evaluated, never real attributes — so __getattr__
    stays the runtime resolver. Regenerate via CodeGenerator.update_render_funcs().
    """

    _do_save: "_LazyRenderFunc"
    address_to_call_parse: "_LazyRenderFunc"
    address_to_class: "_LazyRenderFunc"
    address_to_function: "_LazyRenderFunc"
    address_to_general_parse: "_LazyRenderFunc"
    address_to_module: "_LazyRenderFunc"
    button: "_LazyRenderFunc"
    call_dict_to_save: "_LazyRenderFunc"
    caller_to_address: "_LazyRenderFunc"
    chain_cls_load: "_LazyRenderFunc"
    class_to_address: "_LazyRenderFunc"
    class_to_address_incl_overrides: "_LazyRenderFunc"
    class_to_var_dict: "_LazyRenderFunc"
    cls_to_cst: "_LazyRenderFunc"
    cst_to_address: "_LazyRenderFunc"
    cst_to_cls: "_LazyRenderFunc"
    cst_to_fn: "_LazyRenderFunc"
    cst_to_mod: "_LazyRenderFunc"
    cst_to_ref: "_LazyRenderFunc"
    dict_to_cst: "_LazyRenderFunc"
    do_recompile: "_LazyRenderFunc"
    draw_app_model: "_LazyRenderFunc"
    draw_blank: "_LazyRenderFunc"
    draw_blit_debug: "_LazyRenderFunc"
    draw_bool: "_LazyRenderFunc"
    draw_collection: "_LazyRenderFunc"
    draw_comment: "_LazyRenderFunc"
    draw_context_menu: "_LazyRenderFunc"
    draw_debug_label: "_LazyRenderFunc"
    draw_drag_drop_target: "_LazyRenderFunc"
    draw_draw_state: "_LazyRenderFunc"
    draw_draw_state_info: "_LazyRenderFunc"
    draw_drop_down_item: "_LazyRenderFunc"
    draw_dropdown: "_LazyRenderFunc"
    draw_enum: "_LazyRenderFunc"
    draw_enum_tabs: "_LazyRenderFunc"
    draw_float: "_LazyRenderFunc"
    draw_float_ctx: "_LazyRenderFunc"
    draw_function: "_LazyRenderFunc"
    draw_int: "_LazyRenderFunc"
    draw_jump_to: "_LazyRenderFunc"
    draw_lsd_studio: "_LazyRenderFunc"
    draw_main: "_LazyRenderFunc"
    draw_managed_window: "_LazyRenderFunc"
    draw_mapping_proxy: "_LazyRenderFunc"
    draw_module: "_LazyRenderFunc"
    draw_none: "_LazyRenderFunc"
    draw_parameter: "_LazyRenderFunc"
    draw_pending: "_LazyRenderFunc"
    draw_pending_texture: "_LazyRenderFunc"
    draw_property: "_LazyRenderFunc"
    draw_search: "_LazyRenderFunc"
    draw_single: "_LazyRenderFunc"
    draw_str: "_LazyRenderFunc"
    draw_style_manager: "_LazyRenderFunc"
    draw_tab_bar: "_LazyRenderFunc"
    draw_tensor: "_LazyRenderFunc"
    draw_text: "_LazyRenderFunc"
    draw_texture: "_LazyRenderFunc"
    draw_tint_context: "_LazyRenderFunc"
    draw_tuple: "_LazyRenderFunc"
    draw_type: "_LazyRenderFunc"
    draw_usage: "_LazyRenderFunc"
    draw_vis: "_LazyRenderFunc"
    draw_with_modes: "_LazyRenderFunc"
    empty: "_LazyRenderFunc"
    eval_function: "_LazyRenderFunc"
    fn_to_cst: "_LazyRenderFunc"
    focus: "_LazyRenderFunc"
    function_to_address: "_LazyRenderFunc"
    general_parse_to_address: "_LazyRenderFunc"
    general_parse_to_str: "_LazyRenderFunc"
    load_cst_module: "_LazyRenderFunc"
    mod_to_cst: "_LazyRenderFunc"
    module_to_address: "_LazyRenderFunc"
    parse_source_to_general: "_LazyRenderFunc"
    path_to_address: "_LazyRenderFunc"
    pending_window: "_LazyRenderFunc"
    recompile_caller_fn: "_LazyRenderFunc"
    recompile_cls_fn: "_LazyRenderFunc"
    recompile_fn: "_LazyRenderFunc"
    recompile_mod_fn: "_LazyRenderFunc"
    ref_to_cst: "_LazyRenderFunc"
    rf_address_to_dict: "_LazyRenderFunc"
    rf_bytes_to_str: "_LazyRenderFunc"
    rf_dict_to_address: "_LazyRenderFunc"
    rf_dict_to_path: "_LazyRenderFunc"
    rf_dict_to_str: "_LazyRenderFunc"
    rf_path_to_bytes: "_LazyRenderFunc"
    rf_path_to_dict: "_LazyRenderFunc"
    rf_str_to_bytes: "_LazyRenderFunc"
    rf_str_to_dict: "_LazyRenderFunc"
    run_button: "_LazyRenderFunc"
    run_chain: "_LazyRenderFunc"
    save_file_fn: "_LazyRenderFunc"
    save_span_fn: "_LazyRenderFunc"
    str_to_general_parse: "_LazyRenderFunc"
    test_columns: "_LazyRenderFunc"
    test_widget: "_LazyRenderFunc"
    text: "_LazyRenderFunc"
    unsort_dict_alphabetically: "_LazyRenderFunc"
    var_dict_to_class: "_LazyRenderFunc"

    def __getattr__(self, name):
        return _LazyRenderFunc(name)



# Reference render funcs by symbol without importing their module:
#     from src.lsd.gl_gui.render_funcs import RenderFuncs
#     @window(render_func=RenderFuncs.draw_type)
RenderFuncs = _RenderFuncs()


class CodeGenerator:
    """Headless code generation over the app's own code-IO lifecycle.

    update_render_funcs() rewrites the _RenderFuncs class above so every
    registered @render_func shows up as a real, IDE-visible member — that's what
    makes `RenderFuncs.<name>` autocomplete. It reads/writes through the same
    Address → load → save-span path the in-app code editors use, just without
    imgui (via each IO node's __wrapped__ bare function).

    The generated members are string annotations (`name: "_LazyRenderFunc"`), so
    they are pure IDE hints: never evaluated, never real attributes, never
    shadowing __getattr__ — which stays the actual runtime resolver. Nothing to
    recompile or hotswap; runtime behaviour is unchanged by the generation.
    """

    @staticmethod
    def _render_funcs_class_source(names):
        lines = [
            "class _RenderFuncs:",
            '    """`RenderFuncs.draw_type` -> a _LazyRenderFunc handle, no import required.',
            "",
            "    The annotated members below are generated by CodeGenerator (one per",
            "    registered @render_func) so IDEs autocomplete RenderFuncs.<name>. They are",
            "    string annotations — never evaluated, never real attributes — so __getattr__",
            "    stays the runtime resolver. Regenerate via CodeGenerator.update_render_funcs().",
            '    """',
            "",
        ]
        lines += [f'    {name}: "_LazyRenderFunc"' for name in names]
        lines += [
            "",
            "    def __getattr__(self, name):",
            "        return _LazyRenderFunc(name)",
        ]
        return "\n".join(lines) + "\n"

    @staticmethod
    def update_render_funcs():
        """Regenerate the _RenderFuncs class body in this file from the live
        registry. Returns the written Address."""
        import libcst as cst
        from src.lsd.gl_gui.view.core_conversion.address import to_address
        from src.lsd.gl_gui.view.core_conversion.file_converters import save_span_fn

        ref = to_address(_RenderFuncs)
        if ref is None:
            raise RuntimeError("Could not resolve the source location of _RenderFuncs")

        names = sorted(n for n in Melty.render_funcs_by_name if n.isidentifier())
        source = CodeGenerator._render_funcs_class_source(names)

        # Round-trip through libcst parser to normalize + optimise on disk.
        source = cst.parse_module(source).code

        # save_span_fn is a @render_func; .__wrapped__ is the bare span-spelle
        # (no imgui / draw_state) - the headless edge of the same save node the
        # in-app editor saves through.
        save_span_fn.__wrapped__(source, ref=ref)
        return ref
