"""Symbol access to @render_func renderers without importing their module.

`RenderFuncs.draw_type` returns a lazy handle that resolves at call time from the
render-func registry (auto-populated by the @render_func decorator). This
sidesteps import cycles: referencing a render func here never triggers an import
of whatever heavy module defines it.

This module never imports Melty — the dependency runs the other way. Melty owns
and manages the registry; we reach it through the lightweight Core.melty handle
so that referencing render funcs stays a low-level concern, not one that reaches
back up into the Melty hub.

CodeGenerator regenerates the _RenderFuncs class in THIS file so every registered
render func shows up as a real, IDE-visible member — kept in its own file so the
generator only ever rewrites this small module, never melty.py.
"""
from src.lsd.gl_gui.view.core_views.decoration.core_decoration import Core


class _LazyRenderFunc:
    """A by-name handle to a @render_func, resolved on first use.

    Behaves like the render func itself: callable with the same signature and
    carrying the right __name__ (the view system reads that). Resolution is
    deferred to call time, by which point every module has imported and
    self-registered into the registry (reached via Core.melty) — so referencing
    one of these never triggers an import and never participates in an import cycle.
    """

    __slots__ = ("__name__", "_fn")

    def __init__(self, name):
        self.__name__ = name
        self._fn = None

    def _resolve(self):
        if self._fn is None:
            fn = Core.melty.render_funcs_by_name.get(self.__name__)
            if fn is None:
                raise AttributeError(
                    f"No @render_func named {self.__name__!r} is registered")
            self._fn = fn
        return self._fn

    def __call__(self, *args, **kwargs):
        return self._resolve()(*args, **kwargs)

    def __getattr__(self, item):
        # Forward real attributes (e.g. _load_data/_save_data) to the resolved
        # func, but never dunders; copy/pickle probes (__deepcopy__, etc.) must
        # fall through to default handling rather than force early resolution.
        if item.startswith("__") and item.endswith("__"):
            raise AttributeError(item)
        return getattr(self._resolve(), item)


class _RenderFuncs:
    """`RenderFuncs.draw_type` -> a _LazyRenderFunc handle, no import required.

    The members below are generated by CodeGenerator (one per registered
    @render_func) so IDEs autocomplete RenderFuncs.<name>. Each is a real class
    attribute; __getattr__ is the fallback for any render func added since the
    last regeneration. Regenerate via CodeGenerator.update_render_funcs().
    """
    _do_save = _LazyRenderFunc("_do_save")
    address_to_call_parse = _LazyRenderFunc("address_to_call_parse")
    address_to_class = _LazyRenderFunc("address_to_class")
    address_to_function = _LazyRenderFunc("address_to_function")
    address_to_general_parse = _LazyRenderFunc("address_to_general_parse")
    address_to_module = _LazyRenderFunc("address_to_module")
    button = _LazyRenderFunc("button")
    call_dict_to_save = _LazyRenderFunc("call_dict_to_save")
    caller_to_address = _LazyRenderFunc("caller_to_address")
    chain_cls_load = _LazyRenderFunc("chain_cls_load")
    class_to_address = _LazyRenderFunc("class_to_address")
    class_to_address_incl_overrides = _LazyRenderFunc("class_to_address_incl_overrides")
    class_to_var_dict = _LazyRenderFunc("class_to_var_dict")
    cls_to_cst = _LazyRenderFunc("cls_to_cst")
    cst_to_address = _LazyRenderFunc("cst_to_address")
    cst_to_cls = _LazyRenderFunc("cst_to_cls")
    cst_to_fn = _LazyRenderFunc("cst_to_fn")
    cst_to_mod = _LazyRenderFunc("cst_to_mod")
    cst_to_ref = _LazyRenderFunc("cst_to_ref")
    dict_to_cst = _LazyRenderFunc("dict_to_cst")
    do_recompile = _LazyRenderFunc("do_recompile")
    draw_app_model = _LazyRenderFunc("draw_app_model")
    draw_blank = _LazyRenderFunc("draw_blank")
    draw_blit_debug = _LazyRenderFunc("draw_blit_debug")
    draw_bool = _LazyRenderFunc("draw_bool")
    draw_collection = _LazyRenderFunc("draw_collection")
    draw_comment = _LazyRenderFunc("draw_comment")
    draw_context_menu = _LazyRenderFunc("draw_context_menu")
    draw_debug_label = _LazyRenderFunc("draw_debug_label")
    draw_drag_drop_target = _LazyRenderFunc("draw_drag_drop_target")
    draw_draw_state = _LazyRenderFunc("draw_draw_state")
    draw_draw_state_info = _LazyRenderFunc("draw_draw_state_info")
    draw_drop_down_item = _LazyRenderFunc("draw_drop_down_item")
    draw_dropdown = _LazyRenderFunc("draw_dropdown")
    draw_enum = _LazyRenderFunc("draw_enum")
    draw_enum_tabs = _LazyRenderFunc("draw_enum_tabs")
    draw_float = _LazyRenderFunc("draw_float")
    draw_float_ctx = _LazyRenderFunc("draw_float_ctx")
    draw_function = _LazyRenderFunc("draw_function")
    draw_int = _LazyRenderFunc("draw_int")
    draw_jump_to = _LazyRenderFunc("draw_jump_to")
    draw_lsd_studio = _LazyRenderFunc("draw_lsd_studio")
    draw_main = _LazyRenderFunc("draw_main")
    draw_managed_window = _LazyRenderFunc("draw_managed_window")
    draw_mapping_proxy = _LazyRenderFunc("draw_mapping_proxy")
    draw_module = _LazyRenderFunc("draw_module")
    draw_none = _LazyRenderFunc("draw_none")
    draw_parameter = _LazyRenderFunc("draw_parameter")
    draw_pending = _LazyRenderFunc("draw_pending")
    draw_pending_texture = _LazyRenderFunc("draw_pending_texture")
    draw_property = _LazyRenderFunc("draw_property")
    draw_search = _LazyRenderFunc("draw_search")
    draw_single = _LazyRenderFunc("draw_single")
    draw_str = _LazyRenderFunc("draw_str")
    draw_style_manager = _LazyRenderFunc("draw_style_manager")
    draw_tab_bar = _LazyRenderFunc("draw_tab_bar")
    draw_tensor = _LazyRenderFunc("draw_tensor")
    draw_text = _LazyRenderFunc("draw_text")
    draw_texture = _LazyRenderFunc("draw_texture")
    draw_tint_context = _LazyRenderFunc("draw_tint_context")
    draw_tuple = _LazyRenderFunc("draw_tuple")
    draw_type = _LazyRenderFunc("draw_type")
    draw_usage = _LazyRenderFunc("draw_usage")
    draw_vis = _LazyRenderFunc("draw_vis")
    draw_with_modes = _LazyRenderFunc("draw_with_modes")
    empty = _LazyRenderFunc("empty")
    eval_function = _LazyRenderFunc("eval_function")
    fn_to_cst = _LazyRenderFunc("fn_to_cst")
    focus = _LazyRenderFunc("focus")
    function_to_address = _LazyRenderFunc("function_to_address")
    general_parse_to_address = _LazyRenderFunc("general_parse_to_address")
    general_parse_to_str = _LazyRenderFunc("general_parse_to_str")
    load_cst_module = _LazyRenderFunc("load_cst_module")
    mod_to_cst = _LazyRenderFunc("mod_to_cst")
    module_to_address = _LazyRenderFunc("module_to_address")
    parse_source_to_general = _LazyRenderFunc("parse_source_to_general")
    path_to_address = _LazyRenderFunc("path_to_address")
    pending_window = _LazyRenderFunc("pending_window")
    recompile_caller_fn = _LazyRenderFunc("recompile_caller_fn")
    recompile_cls_fn = _LazyRenderFunc("recompile_cls_fn")
    recompile_fn = _LazyRenderFunc("recompile_fn")
    recompile_mod_fn = _LazyRenderFunc("recompile_mod_fn")
    ref_to_cst = _LazyRenderFunc("ref_to_cst")
    rf_address_to_dict = _LazyRenderFunc("rf_address_to_dict")
    rf_bytes_to_str = _LazyRenderFunc("rf_bytes_to_str")
    rf_dict_to_address = _LazyRenderFunc("rf_dict_to_address")
    rf_dict_to_path = _LazyRenderFunc("rf_dict_to_path")
    rf_dict_to_str = _LazyRenderFunc("rf_dict_to_str")
    rf_path_to_bytes = _LazyRenderFunc("rf_path_to_bytes")
    rf_path_to_dict = _LazyRenderFunc("rf_path_to_dict")
    rf_str_to_bytes = _LazyRenderFunc("rf_str_to_bytes")
    rf_str_to_dict = _LazyRenderFunc("rf_str_to_dict")
    run_button = _LazyRenderFunc("run_button")
    run_chain = _LazyRenderFunc("run_chain")
    save_file_fn = _LazyRenderFunc("save_file_fn")
    save_span_fn = _LazyRenderFunc("save_span_fn")
    str_to_general_parse = _LazyRenderFunc("str_to_general_parse")
    test_columns = _LazyRenderFunc("test_columns")
    test_widget = _LazyRenderFunc("test_widget")
    text = _LazyRenderFunc("text")
    unsort_dict_alphabetically = _LazyRenderFunc("unsort_dict_alphabetically")
    var_dict_to_class = _LazyRenderFunc("var_dict_to_class")

    def __getattr__(self, name):
        return _LazyRenderFunc(name)



# Reference render funcs by symbol without importing their module:
#     from src.lsd.gl_gui.render_funcs import RenderFuncs
#     @window(render_func=RenderFuncs.draw_type)
RenderFuncs = _RenderFuncs()


class CodeGenerator:
    """Headless code generation over the app's own cst↔dict round-trip.

    update_render_funcs() rewrites the _RenderFuncs class above so every
    registered @render_func shows up as a real, IDE-visible member — that's what
    makes `RenderFuncs.<name>` autocomplete. The edit runs through the same
    converters the in-app editor uses, just without imgui:

        source span → cst.ClassDef → cst_classdef_to_dict → (add a key per name)
                    → dict_to_cst_classdef → source span

    Each member is a real assignment (`name = _LazyRenderFunc("name")` /
    `name = _LazyMode("name")`), so it is a genuine class attribute the IDE can
    see; __getattr__ stays as the fallback for anything added since the last
    regeneration. Nothing to recompile or hotswap — runtime behaviour is unchanged.
    """

    @staticmethod
    def _regenerate(target_cls, names, expr_for):
        """Rewrite `target_cls`'s body in this file so it has one assignment per
        name, via the same cst↔dict round-trip the in-app editor uses:

            source span → cst.ClassDef → cst_classdef_to_dict → (add a key per
                        name) → dict_to_cst_classdef → source span

        Existing class vars are stripped first so only the Add path runs (clean +
        idempotent). `expr_for(name)` returns the assignment's RHS source.
        Returns the written Address."""
        import libcst as cst
        from src.lsd.gl_gui.view.core_conversion.address import to_address
        from src.lsd.gl_gui.view.core_conversion.file_converters import (
            load_text, save_span_fn)
        from src.lsd.gl_gui.view.core_conversion.libcst_conversion import (
            cst_classdef_to_dict, dict_to_cst_classdef)

        class _StripClassVars(cst.CSTTransformer):
            def leave_SimpleStatementLine(self, original, updated):
                if len(updated.body) == 1 and isinstance(
                        updated.body[0], (cst.Assign, cst.AnnAssign)):
                    return cst.RemoveFromParent()
                return updated

        ref = to_address(target_cls)
        if ref is None:
            raise RuntimeError(
                f"Could not resolve the source location of {target_cls.__name__}")

        module = cst.parse_module(load_text(ref))
        classdef = next(s for s in module.body if isinstance(s, cst.ClassDef))
        classdef = classdef.visit(_StripClassVars())

        members = cst_classdef_to_dict(classdef)
        for name in names:
            members[name] = cst.parse_expression(expr_for(name))
        new_classdef = dict_to_cst_classdef(members)

        new_module = module.with_changes(body=[
            new_classdef if isinstance(s, cst.ClassDef) else s for s in module.body])

        # save_span_fn is a @render_func; .__wrapped__ is the bare span-spelle
        # (no imgui / draw_state) - the headless edge of the same save node the
        # in-app editor saves through.
        save_span_fn.__wrapped__(new_module.code, ref=ref)
        return ref

    @staticmethod
    def update_render_funcs():
        """Regenerate _RenderFuncs from the live @render_func registry."""
        names = sorted(n for n in Core.melty.render_funcs_by_name if n.isidentifier())
        return CodeGenerator._regenerate(
            _RenderFuncs, names, lambda n: f'_LazyRenderFunc("{n}")')

    @staticmethod
    def update_modes():
        """Regenerate _Modes (in modes.py) from the live Mode enum."""
        from src.lsd.gl_gui.view.mode import Mode
        from src.lsd.gl_gui.modes import _Modes
        names = sorted(n for n in Mode.__members__ if n.isidentifier())
        return CodeGenerator._regenerate(
            _Modes, names, lambda n: f'_LazyMode("{n}")')
